external-dns:
  provider: cloudflare
  txtOwnerId: homelab
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: cloudflare_api_token
  extraArgs:
    - --ingress-class=public
    - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
