firefly-iii:
  env:
    TZ: America/New_York
  ingress:
    main:
      enabled: true
      ingressClassName: private-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: 100.74.37.74
        hajimari.io/icon: cash
      hosts:
        - host: &host firefly.mbund.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: firefly-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      storageClass: longhorn
    uploads:
      enabled: true
      storageClass: longhorn
