ingress-nginx:
  controller:
    config:
      use-forwarded-headers: "true"
      custom-http-errors: >-
        401,403,404,500,501,502,503
    ingressClassResource:
      name: private
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-private"
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      type: ClusterIP
      clusterIP: 10.43.0.60
    extraContainers:
      - name: ts-sidecar
        imagePullPolicy: Always
        image: ghcr.io/tailscale/tailscale:latest
        env:
        - name: TS_HOSTNAME
          value: homelab-router
        - name: TS_KUBE_SECRET
          value: tailscale-secret
        - name: TS_USERSPACE
          value: "false"
        # - name: TS_DEBUG_FIREWALL_MODE
        #   value: auto
        # - name: TS_AUTH_ONCE
        #   value: "true"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        securityContext:
          privileged: true
  defaultBackend:
    enabled: true
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: latest
    extraEnvs:
      - name: TEMPLATE_NAME
        value: connection
      - name: SHOW_DETAILS
        value: "true"
