ingress-nginx:
  controller:
    config:
      use-forwarded-headers: "true"
      custom-http-errors: >-
        401,403,404,500,501,502,503
    ingressClassResource:
      name: private
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-private"
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      type: ClusterIP
      clusterIP: 10.43.0.60
  defaultBackend:
    enabled: true
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: latest
    extraEnvs:
      - name: TEMPLATE_NAME
        value: connection
      - name: SHOW_DETAILS
        value: "true"
