ingress-nginx:
  controller:
    config:
      use-proxy-protocol: "true"
      custom-http-errors: >-
        401,403,404,500,501,502,503
    ingressClassResource:
      name: public
      enabled: true
      default: false
      controllerValue: "k8s.io/ingress-nginx-public"
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      type: ClusterIP
      clusterIP: 10.43.0.62
  defaultBackend:
    enabled: true
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: latest
    extraEnvs:
      - name: TEMPLATE_NAME
        value: app-down
      - name: SHOW_DETAILS
        value: "true"
  tcp:
    8883: "emqx/emqx:8883:PROXY:PROXY"
    25: "mailserver/docker-mailserver:25:PROXY:"
    143: "mailserver/docker-mailserver:143:PROXY:"
    587: "mailserver/docker-mailserver:587:PROXY:"
    993: "mailserver/docker-mailserver:993:PROXY:"
