apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: longhorn
