kube-prometheus-stack:
  grafana:
    adminPassword: null
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Grafana
        hajimari.io/icon: chart-bar
      hosts:
        - &host grafana.127-0-0-1.nip.io
      tls:
        - secretName: grafana-general-tls
          hosts:
            - *host
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
    grafana.ini:
      server:
        root_url: https://grafana.127-0-0-1.nip.io

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
