apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw
  annotations:
    hajimari.io/icon: draw
spec:
  ingressClassName: private-nginx
  rules:
    - host: &host draw.homelab
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: excalidraw
                port:
                  name: http
