apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/icon: draw
spec:
  ingressClassName: nginx
  rules:
    - host: &host draw.127-0-0-1.nip.io
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: excalidraw
                port:
                  name: http
  tls:
    - secretName: excalidraw-tls-certificate
      hosts:
        - *host
