ingress-nginx:
  controller:
    ingressClassResource:
      name: private-nginx # default: nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/private-ingress-nginx" # default: k8s.io/ingress-nginx
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
