kube-prometheus-stack:
  grafana:
    adminPassword: null
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
        hajimari.io/appName: Grafana
        hajimari.io/icon: chart-bar
        hajimari.io/group: External
      hosts:
        - &host grafana.mbund.org
      tls:
        - secretName: grafana-general-tls
          hosts:
            - *host
    persistence:
      enabled: true
      storageClass: longhorn
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
    grafana.ini:
      server:
        root_url: https://grafana.mbund.org
      auth.anonymous:
        enabled: true

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
