kube-prometheus-stack:
  grafana:
    adminPassword: null
    defaultDashboardsEnabled: false
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
      hosts:
        - &host grafana.mbund.org
      tls:
        - secretName: grafana-general-tls
          hosts:
            - *host
    persistence:
      enabled: true
      storageClass: longhorn
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
    grafana.ini:
      server:
        root_url: https://grafana.mbund.org
      auth.anonymous:
        enabled: true
      security:
        allow_embedding: true
      rendering:
        server_url: http://grafana-image-renderer:8081/render
        callback_url: http://localhost:3000

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
    ingress:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
      hosts:
        - &host prometheus.mbund.org
      tls:
        - secretName: prometheus-general-tls
          hosts:
            - *host
