vaultwarden:
  ingress:
    main:
      enabled: true
      ingressClassName: private-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: homelab.tail22829.ts.net
        hajimari.io/icon: shield-account
      hosts:
        - host: &host password.mbund.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: vaultwarden-tls-certificate
          hosts:
            - *host
  persistence:
    enabled: true
    storageClass: longhorn
