vaultwarden:
  env:
    DOMAIN: https://vaultwarden.mbund.org
  ingress:
    main:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
      hosts:
        - host: &host vaultwarden.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub/negotiate
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub
              pathType: Prefix
              service:
                port: 3012
      tls:
        - secretName: vaultwarden-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      storageClass: longhorn
