vaultwarden:
  ingress:
    main:
      enabled: true
      ingressClassName: private-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: homelab.tail22829.ts.net
        hajimari.io/icon: shield-account
      hosts:
        - host: &host password.mbund.org
          paths: &paths
            - path: /
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub/negotiate
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub
              pathType: Prefix
              service:
                port: 3012
        - host: &alias password.homelab.tail22829.ts.net
          paths: *paths
      tls:
        - secretName: vaultwarden-tls-certificate
          hosts:
            - *host
            - *alias
  persistence:
    config:
      enabled: true
      storageClass: longhorn
