nextcloud:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: public
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: relay.mbund.org
      hajimari.io/icon: simple-icons:nextcloud
      hajimari.io/group: External
    hosts:
      - host: &host cloud.mbund.org
    tls:
      - secretName: nextcloud-tls-certificate
        hosts:
          - *host
  customConfigs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          0 => '127.0.0.1',
          1 => '10.0.0.0/8',
        ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
      );
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'default_phone_region' => 'US',
        'config_is_read_only' => true,
      );
  storage:
    nextcloud:
      className: longhorn
    nextcloudData:
      className: longhorn
