version: "3"

tasks:
  bootstrap:
    cmds:
      - kubectl create namespace argocd --dry-run=client --output=yaml | kubectl apply -f -
      - task: bootstrap:argocd
      - task: bootstrap:root

  bootstrap:argocd:
    internal: true
    dir: bootstrap/argocd
    cmds:
      - ./apply.sh

  bootstrap:root:
    internal: true
    dir: bootstrap/root
    cmds:
      - ./apply.sh

  dev:
    aliases:
      - default
    dir: dev
    cmds:
      - k3d cluster start homelab-dev || k3d cluster create --config k3d-dev.yaml
      - k3d kubeconfig get homelab-dev > kubeconfig-dev.yaml
      - task: bootstrap

  dev:cleanup:
    cmds:
      - k3d cluster delete homelab-dev

  scripts:argocd-admin-password:
    cmds:
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

  scripts:vault-root-token:
    cmds:
      - kubectl get secrets vault-unseal-keys -n vault -o jsonpath='{.data.vault-root}' | base64 --decode

  dev:git-configuration:
    cmds:
      - git remote add sandbox https://git.127-0-0-1.nip.io/ops/homelab
      - git config http.https://git.127-0-0-1.nip.io.sslVerify false
