version: '3'

tasks:
  bootstrap:
    cmds:
      - kubectl create namespace argocd --dry-run=client --output=yaml | kubectl apply -f -
      - task: bootstrap:argocd
      - task: bootstrap:root

  bootstrap:argocd:
    internal: true
    dir: bootstrap/argocd
    cmds:
      - ./apply.sh

  bootstrap:root:
    internal: true
    dir: bootstrap/root
    cmds:
      - ./apply.sh

  dev:
    aliases:
      - default
    dir: dev
    env:
      KUBECONFIG: /home/mbund/dev/mbund/homelab/dev/kubeconfig-dev.yaml
    cmds:
      - echo $KUBECONFIG
      - k3d cluster start homelab-dev || k3d cluster create --config k3d-dev.yaml
      - k3d kubeconfig get homelab-dev > kubeconfig-dev.yaml
      - task: bootstrap

  dev:cleanup:
    cmds:
      - k3d cluster delete homelab-dev
