loki-stack:
  loki:
    serviceMonitor:
      enabled: true
  promtail:
    initContainer:
      - name: init
        image: docker.io/busybox:1.33
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - sysctl -w fs.inotify.max_user_instances=512
        securityContext:
          privileged: true
