postgres-operator-ui:
  envs:
    appUrl: https://postgres.mbund.org
    operatorApiUrl: http://zolando-postgres-operator:8080
    targetNamespace: zolando-postgres-operator
    teams:
      - sre
  ingress:
    enabled: true
    ingressClassName: private
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
      mbund.org/dns-server: internal
      hajimari.io/appName: Zolando Postgres Operator
      hajimari.io/icon: database-cog
      hajimari.io/group: Internal
    hosts:
      - host: &host postgres.mbund.org
        paths:
          - /
    tls:
      - secretName: zolando-postgres-tls-certificate
        hosts:
          - *host
