ingress-nginx:
  controller:
    ingressClassResource:
      name: public-nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/public-ingress-nginx"
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
