jellyfin:
  global:
    nameOverride: jellyfin
  env:
    TZ: America/New_York
  ingress:
    main:
      enabled: true
      ingressClassName: relay-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
        hajimari.io/appName: Jellyfin
        hajimari.io/icon: filmstrip
      hosts:
        - host: &jellyfin_host jellyfin.mbund.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *jellyfin_host
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
    cache:
      enabled: true
      mountPath: /cache
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
    media:
      enabled: true
      mountPath: /media
      storageClass: longhorn
      accessMode: ReadWriteMany
      existingClaim: shared-media
jellyseerr:
  global:
    nameOverride: jellyseerr
  ingress:
    main:
      enabled: true
      ingressClassName: private-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: 100.74.37.74
        hajimari.io/appName: Jellyseerr
        hajimari.io/icon: filmstrip
      hosts:
        - host: &jellyseer_host jellyseerr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 5055
      tls:
        - secretName: jellyseerr-tls-certificate
          hosts:
            - *jellyseer_host
  persistence:
    config:
      mountPath: /app/config
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
      readOnly: false
radarr:
  global:
    nameOverride: radarr
  ingress:
    main:
      enabled: true
      ingressClassName: private-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: 100.74.37.74
        hajimari.io/appName: Radarr
        hajimari.io/icon: filmstrip
      hosts:
        - host: &radarr_host radarr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 7878
      tls:
        - secretName: radarr-tls-certificate
          hosts:
            - *radarr_host
  probes:
    startup:
      spec:
        initialDelaySeconds: 20
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      readOnly: false
    media:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: longhorn
      existingClaim: shared-media
      mountPath: /media
prowlarr:
  global:
    nameOverride: prowlarr
  persistence:
    config:
      mountPath: /config
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
      readOnly: false
    storage:
      enabled: true
      accessMode: ReadWriteMany
      storageClass: longhorn
      existingClaim: shared-media
      mountPath: /storage
  ingress:
    main:
      enabled: true
      ingressClassName: private-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: 100.74.37.74
        hajimari.io/appName: Prowlarr
        hajimari.io/icon: filmstrip
      hosts:
        - host: &prowlarrr_host prowlarr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 9696
      tls:
        - secretName: prowlarr-tls-certificate
          hosts:
            - *prowlarrr_host
qbittorrent:
  global:
    nameOverride: qbittorrent
  env:
    TZ: America/New_York
    DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
  ingress:
    main:
      enabled: true
      ingressClassName: private-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: 100.74.37.74
        hajimari.io/appName: QBittorrent
        hajimari.io/icon: filmstrip
      hosts:
        - host: &qbittorrent_host qbittorrent.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8080
      tls:
        - secretName: qbittorrent-tls-certificate
          hosts:
            - *qbittorrent_host
  persistence:
    config:
      enabled: true
      retain: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 1Gi
    media:
      enabled: true
      mountPath: /media
      storageClass: longhorn
      accessMode: ReadWriteMany
      existingClaim: shared-media
  addons:
    vpn:
      enabled: true
      env:
        - name: TZ
          value: America/New_York
        - name: VPN_TYPE
          value: wireguard
        - name: VPN_SERVICE_PROVIDER
          value: mullvad
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: wg-private-key
              name: vpn-secret
        - name: WIREGUARD_ADDRESSES
          valueFrom:
            secretKeyRef:
              key: addresses
              name: vpn-secret
        - name: SERVER_CITIES
          valueFrom:
            secretKeyRef:
              key: city
              name: vpn-secret
