jellyfin:
  global:
    nameOverride: jellyfin
  env:
    TZ: America/New_York
  ingress:
    main:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
        hajimari.io/appName: Jellyfin
        hajimari.io/icon: play-box
        hajimari.io/group: External
      hosts:
        - host: &jellyfin_host jellyfin.mbund.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *jellyfin_host
  runtimeClassName: nvidia
  resources:
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1
  service:
    main:
      type: LoadBalancer
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
    cache:
      enabled: true
      mountPath: /cache
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
    media:
      enabled: true
      mountPath: /media
      storageClass: longhorn
      accessMode: ReadWriteMany
      existingClaim: shared-media
jellyseerr:
  global:
    nameOverride: jellyseerr
  ingress:
    main:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
        hajimari.io/appName: Jellyseerr
        hajimari.io/icon: movie-search
        hajimari.io/group: Internal
      hosts:
        - host: &jellyseer_host jellyseerr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 5055
      tls:
        - secretName: jellyseerr-tls-certificate
          hosts:
            - *jellyseer_host
  persistence:
    config:
      mountPath: /app/config
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
      readOnly: false
radarr:
  global:
    nameOverride: radarr
  ingress:
    main:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
        hajimari.io/appName: Radarr
        hajimari.io/icon: movie
        hajimari.io/group: Internal
      hosts:
        - host: &radarr_host radarr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 7878
      tls:
        - secretName: radarr-tls-certificate
          hosts:
            - *radarr_host
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      readOnly: false
    media:
      enabled: true
      accessMode: ReadWriteMany
      storageClass: longhorn
      existingClaim: shared-media
      mountPath: /media
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
  metrics:
    enabled: true
sonarr:
  global:
    nameOverride: sonarr
  ingress:
    main:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
        hajimari.io/appName: Sonarr
        hajimari.io/icon: television-classic
        hajimari.io/group: Internal
      hosts:
        - host: &sonarr_host sonarr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8989
      tls:
        - secretName: sonarr-tls-certificate
          hosts:
            - *sonarr_host
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      readOnly: false
    media:
      enabled: true
      accessMode: ReadWriteMany
      storageClass: longhorn
      existingClaim: shared-media
      mountPath: /media
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
  metrics:
    enabled: true
bazarr:
  global:
    nameOverride: bazarr
  ingress:
    main:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
        hajimari.io/appName: Bazarr
        hajimari.io/icon: subtitles
        hajimari.io/group: Internal
      hosts:
        - host: &bazarr_host bazarr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 6767
      tls:
        - secretName: bazarr-tls-certificate
          hosts:
            - *bazarr_host
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      readOnly: false
    media:
      enabled: true
      accessMode: ReadWriteMany
      storageClass: longhorn
      existingClaim: shared-media
      mountPath: /media
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
lidarr:
  global:
    nameOverride: lidarr
  ingress:
    main:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
        hajimari.io/appName: Lidarr
        hajimari.io/icon: music
        hajimari.io/group: Internal
      hosts:
        - host: &lidarr_host lidarr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8686
      tls:
        - secretName: lidarr-tls-certificate
          hosts:
            - *lidarr_host
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      readOnly: false
    media:
      enabled: true
      accessMode: ReadWriteMany
      storageClass: longhorn
      existingClaim: shared-media
      mountPath: /media
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
  metrics:
    enabled: true
prowlarr:
  global:
    nameOverride: prowlarr
  ingress:
    main:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
        hajimari.io/appName: Prowlarr
        hajimari.io/icon: cloud-search
        hajimari.io/group: Internal
      hosts:
        - host: &prowlarrr_host prowlarr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 9696
      tls:
        - secretName: prowlarr-tls-certificate
          hosts:
            - *prowlarrr_host
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
      readOnly: false
    storage:
      enabled: true
      accessMode: ReadWriteMany
      storageClass: longhorn
      existingClaim: shared-media
      mountPath: /storage
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
qbittorrent:
  global:
    nameOverride: qbittorrent
  env:
    TZ: America/New_York
    DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
  service:
    bittorrent:
      enabled: true
  ingress:
    main:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
        hajimari.io/appName: QBittorrent
        hajimari.io/icon: download-box
        hajimari.io/group: Internal
      hosts:
        - host: &qbittorrent_host qbittorrent.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8080
      tls:
        - secretName: qbittorrent-tls-certificate
          hosts:
            - *qbittorrent_host
  persistence:
    config:
      enabled: true
      retain: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 1Gi
    media:
      enabled: true
      mountPath: /media
      storageClass: longhorn
      accessMode: ReadWriteMany
      existingClaim: shared-media
  addons:
    vpn:
      enabled: true
      env:
        - name: TZ
          value: America/New_York
        - name: VPN_TYPE
          value: wireguard
        - name: VPN_SERVICE_PROVIDER
          value: mullvad
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: wg-private-key
              name: vpn-secret
        - name: WIREGUARD_ADDRESSES
          valueFrom:
            secretKeyRef:
              key: addresses
              name: vpn-secret
        - name: SERVER_CITIES
          valueFrom:
            secretKeyRef:
              key: city
              name: vpn-secret
