external-dns:
  provider: cloudflare
  txtOwnerId: homelab
  cloudflare:
    secretName: cloudflare-api-token
  crd:
    create: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
