apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: /pihole
        property: password
