overleaf:
  env:
    TZ: America/New_York
    SHARELATEX_MONGO_URL: mongodb://overleaf-mongodb-headless:27017/sharelatex
    SHARELATEX_REDIS_HOST: &redis overleaf-redis-headless
    REDIS_HOST: *redis
  ingress:
    main:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
        mbund.org/dns-server: internal
        hajimari.io/appName: Overleaf
        hajimari.io/icon: file-document-edit
        hajimari.io/group: External
      hosts:
        - host: &host overleaf.mbund.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: overleaf-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
  mongodb:
    replicaCount: 1
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
  redis:
    replica:
      replicaCount: 1
