overleaf:
  env:
    TZ: America/New_York
    SHARELATEX_MONGO_URL: mongodb://latex-mongodb-headless:27017/sharelatex
    SHARELATEX_REDIS_HOST: &redis latex-redis-headless
    REDIS_HOST: *redis
  ingress:
    main:
      enabled: true
      ingressClassName: relay-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
        hajimari.io/appName: Overleaf
        hajimari.io/icon: file-document-edit
        hajimari.io/group: External
      hosts:
        - host: &host latex.mbund.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: latex-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
  mongodb:
    architecture: replicaset
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
