apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  labels:
    app.kubernetes.io/name: frigate-config
data:
  config.yml: |
    mqtt:
      enabled: false
    cameras:
      door:
        enabled: true
        ffmpeg:
          inputs:
            - path: rtsp://192.168.1.137:8554/stream1
              roles:
                - record
                - detect
        record:
          enabled: true
        snapshots:
          enabled: true
