apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  labels:
    app.kubernetes.io/name: frigate-config
data:
  config.yml: |
    mqtt:
      enabled: false
    go2rtc:
      streams:
        door:
          - rtsp://192.168.1.137:8554/stream1
          - "ffmpeg:door#audio=opus"
    cameras:
      door:
        ffmpeg:
          output_args:
            record: preset-record-generic-audio-copy
          inputs:
            - path: rtsp://127.0.0.1:8554/door
              input_args: preset-rtsp-restream
              roles:
                - record
                - detect
