apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: docker.io/haproxy:2.8.1
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-configmap
            items:
              - key: haproxy.cfg
                path: haproxy.cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
data:
  haproxy.cfg: |
    global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /var/lib/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

    defaults
            log     global
            mode tcp
            option tcplog
            option  dontlognull
            timeout connect 5000
            timeout client  50000
            timeout server  50000

    frontend https
            bind *:443
            default_backend https_backend
    backend https_backend
            server server1 ingress-nginx-public-controller:443 send-proxy-v2
