apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: runner-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        token: {{` "{{ .token }}" `}}
  data:
    - secretKey: token
      remoteRef:
        key: /gitea
        property: runner-token
