matrix-synapse:
  serverName: mbund.org
  publicServerName: matrix.mbund.org
  ingress:
    className: public-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: homelab-tunnel.mbund.org
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hajimari.io/enable: "false"
    tls:
      - secretName: element-tls-certificate
        hosts:
          - matrix.mbund.org
  wellknown:
    enabled: true
  signingkey:
    job:
      enabled: false
    existingSecret: synapse-signingkey-secret
  postgresql:
    existingSecret: synapse-postgres-secret
    auth:
      existingSecret: synapse-postgres-secret
    primary:
      persistence:
        storageClass: longhorn
  redis:
    auth:
      existingSecret: synapse-redis-secret
  persistence:
    storageClass: longhorn
  extraCommands:
    - "echo POSTGRES"
    - "echo ${POSTGRES_PASSWORD}"
    - "echo REDIS"
    - "echo ${REDIS_PASSWORD}"
