cloudflared:
  image:
    tag: "2023.5.0"
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - hostname: mc.mbund.org
        service: tcp://minecraft-minecraft.minecraft:25565
      - hostname: mbund.org
        service: https://public-ingress-nginx-controller.public-ingress-nginx
        originRequest:
          noTLSVerify: true
      - hostname: "*.mbund.org"
        service: https://public-ingress-nginx-controller.public-ingress-nginx
        originRequest:
          noTLSVerify: true
      - service: http_status:404

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
