nextcloud:
  image:
    tag: 26.0.1-fpm
  nextcloud:
    host: &host cloud.mbund.org
    existingSecret:
      enabled: true
      secretName: admin-secret
    phpConfigs:
      www.conf: |
        [www]
        user = www-data
        group = www-data
        listen = 127.0.0.1:9000

        pm = dynamic
        pm.max_children = 300
        pm.start_servers = 10
        pm.min_spare_servers = 6
        pm.max_spare_servers = 18
        pm.max_requests = 500
        pm.process_idle_timeout = 10s
    configs:
      proxy.config.php: |-
        <?php
        $CONFIG = array (
          'trusted_proxies' => array(
            0 => '127.0.0.1',
            1 => '10.0.0.0/8',
          ),
          'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        );
      custom.config.php: |-
        <?php
        $CONFIG = array (
          'default_phone_region' => 'US',
        );
  ingress:
    enabled: true
    className: relay-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: relay.mbund.org
      hajimari.io/icon: simple-icons:nextcloud
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      nginx.ingress.kubernetes.io/server-snippet: |-
        server_tokens off;
        proxy_hide_header X-Powered-By;
        rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
        rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
        location = /.well-known/carddav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /.well-known/caldav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /robots.txt {
          allow all;
          log_not_found off;
          access_log off;
        }
        location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
          deny all;
        }
        location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
          deny all;
        }
    tls:
      - secretName: nextcloud-tls-certificate
        hosts:
          - *host
  phpClientHttpsFix:
    enabled: true
  startupProbe:
    enabled: true
    failureThreshold: 60
  nginx:
    enabled: true
  internalDatabase:
    enabled: false
  externalDatabase:
    existingSecret:
      enabled: true
      secretName: postgres-secret
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          existingSecret: postgres-secret
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
  redis:
    enabled: true
    auth:
      existingSecret: redis-secret
      existingSecretPasswordKey: redis-password
  persistence:
    enabled: true
    storageClass: longhorn
    nextcloudData:
      enabled: true
      size: 256Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
