nextcloud:
  image:
    tag: 26.0.1-fpm-alpine
  nextcloud:
    host: &host cloud.mbund.org
    existingSecret:
      enabled: true
      secretName: admin-secret
    extraInitContainers:
      - name: set-perms
        image: busybox
        securityContext:
          privileged: true
        command:
          - /bin/sh
          - -c
          - chown -R 82:82 /var/www
        volumeMounts:
          - mountPath: /var/www/
            name: nextcloud-main
            subPath: root
          - mountPath: /var/www/html
            name: nextcloud-main
            subPath: html
          - mountPath: /var/www/html/data
            name: nextcloud-data
            subPath: data
          - mountPath: /var/www/html/config
            name: nextcloud-main
            subPath: config
          - mountPath: /var/www/html/custom_apps
            name: nextcloud-main
            subPath: custom_apps
          - mountPath: /var/www/tmp
            name: nextcloud-main
            subPath: tmp
          - mountPath: /var/www/html/themes
            name: nextcloud-main
            subPath: themes
          - mountPath: /var/www/html/config/custom.config.php
            name: nextcloud-config
            subPath: custom.config.php
          - mountPath: /var/www/html/config/proxy.config.php
            name: nextcloud-config
            subPath: proxy.config.php
          - mountPath: /var/www/html/config/.htaccess
            name: nextcloud-config
            subPath: .htaccess
          - mountPath: /var/www/html/config/apache-pretty-urls.config.php
            name: nextcloud-config
            subPath: apache-pretty-urls.config.php
          - mountPath: /var/www/html/config/apcu.config.php
            name: nextcloud-config
            subPath: apcu.config.php
          - mountPath: /var/www/html/config/apps.config.php
            name: nextcloud-config
            subPath: apps.config.php
          - mountPath: /var/www/html/config/autoconfig.php
            name: nextcloud-config
            subPath: autoconfig.php
          - mountPath: /var/www/html/config/redis.config.php
            name: nextcloud-config
            subPath: redis.config.php
          - mountPath: /var/www/html/config/smtp.config.php
            name: nextcloud-config
            subPath: smtp.config.php
    extraSidecarContainers:
      - name: nextcloud-logger
        image: busybox
        command:
          - /bin/sh
          - -c
          - while ! test -f "/run/nextcloud/data/nextcloud.log"; do sleep 1; done; tail -n+1 -f /run/nextcloud/data/nextcloud.log
        volumeMounts:
          - name: nextcloud-data
            mountPath: /run/nextcloud/data
    phpConfigs:
      www.conf: |
        [www]
        user = www-data
        group = www-data
        listen = 127.0.0.1:9000

        pm = dynamic
        pm.max_children = 300
        pm.start_servers = 10
        pm.min_spare_servers = 6
        pm.max_spare_servers = 18
        pm.max_requests = 500
        pm.process_idle_timeout = 10s
    configs:
      proxy.config.php: |-
        <?php
        $CONFIG = array (
          'trusted_proxies' => array(
            0 => '127.0.0.1',
            1 => '10.0.0.0/8',
          ),
          'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        );
      custom.config.php: |-
        <?php
        $CONFIG = array (
          'default_phone_region' => 'US',
        );
  ingress:
    enabled: true
    className: relay-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: relay.mbund.org
      hajimari.io/icon: simple-icons:nextcloud
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      nginx.ingress.kubernetes.io/server-snippet: |-
        server_tokens off;
        proxy_hide_header X-Powered-By;
        rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
        rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
        location = /.well-known/carddav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /.well-known/caldav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /robots.txt {
          allow all;
          log_not_found off;
          access_log off;
        }
        location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
          deny all;
        }
        location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
          deny all;
        }
    tls:
      - secretName: nextcloud-tls-certificate
        hosts:
          - *host
  phpClientHttpsFix:
    enabled: true
  livenessProbe:
    initialDelaySeconds: 180
  readinessProbe:
    initialDelaySeconds: 180
  nginx:
    enabled: true
  internalDatabase:
    enabled: false
  externalDatabase:
    existingSecret:
      enabled: true
      secretName: postgres-secret
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          existingSecret: postgres-secret
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
  redis:
    enabled: true
    auth:
      existingSecret: redis-secret
      existingSecretPasswordKey: redis-password
  persistence:
    enabled: true
    storageClass: longhorn
    nextcloudData:
      enabled: true
      size: 256Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
