nextcloud:
  nextcloud:
    host: &host drive.mbund.org
    existingSecret:
      enabled: true
      secretName: admin-secret
    mail:
      enabled: true
      fromAddress: nextcloud
      domain: mbund.org
      smtp:
        host: smtp.mbund.org
        secure: tls
        port: 587
        authtype: PLAIN
    phpConfigs:
      zzz-custom.ini: |-
        upload_max_filesize=16G
        post_max_size=16G
        memory_limit=2048M
    configs:
      proxy.config.php: |-
        <?php
        $CONFIG = array (
          'trusted_proxies' => array(
            0 => '127.0.0.1',
            1 => '10.0.0.0/8',
          ),
          'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          'overwritehost' => 'drive.mbund.org',
          'overwriteprotocol' => 'https',
        );
      custom.config.php: |-
        <?php
        $CONFIG = array (
          'default_phone_region' => 'US',
          'trusted_domains' => array (
            0 => 'drive.mbund.org'
          ),
          'mail_smtptimeout' => '30',
          'app.mail.smtp.timeout' => 30,
        );
  ingress:
    enabled: true
    className: public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: relay.mbund.org

      # .well-known/webfinger and .well-known/nodeinfo both return 404s along with valid json,
      # but I set up ingress-nginx to display http errors as nice pages. This behavior needs
      # to be disabled for these two endpoints to work.
      nginx.ingress.kubernetes.io/custom-http-errors: "401,403,500,501,502,503"
      nginx.ingress.kubernetes.io/disable-proxy-intercept-errors: "true"
      nginx.ingress.kubernetes.io/default-backend: nextcloud

      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      nginx.ingress.kubernetes.io/server-snippet: |-
        server_tokens off;
        proxy_hide_header X-Powered-By;
        rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
        rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
        location = /.well-known/carddav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /.well-known/caldav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /robots.txt {
          allow all;
          log_not_found off;
          access_log off;
        }
        location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
          deny all;
        }
        location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
          deny all;
        }
    tls:
      - secretName: nextcloud-tls-certificate
        hosts:
          - *host
  internalDatabase:
    enabled: false
  externalDatabase:
    existingSecret:
      enabled: true
      secretName: postgres-secret
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          existingSecret: postgres-secret
  redis:
    enabled: true
    auth:
      existingSecret: redis-secret
      existingSecretPasswordKey: redis-password
  startupProbe:
    enabled: true
    initialDelaySeconds: 120
    failureThreshold: 50
  persistence:
    enabled: true
    storageClass: longhorn
    nextcloudData:
      enabled: true
      size: 80Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
