nextcloud:
  image:
    tag: 26.0.1-fpm
  nextcloud:
    host: &host cloud.mbund.org
    existingSecret:
      enabled: true
      secretName: admin-secret
  ingress:
    enabled: true
    className: relay-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: relay.mbund.org
      hajimari.io/icon: simple-icons:nextcloud
    tls:
      - secretName: nextcloud-tls-certificate
        hosts:
          - *host
  startupProbe:
    enabled: true
    failureThreshold: 60
  nginx:
    enabled: true
  internalDatabase:
    enabled: false
  externalDatabase:
    existingSecret:
      enabled: true
      secretName: postgres-secret
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          existingSecret: postgres-secret
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
  redis:
    enabled: true
    auth:
      existingSecret: redis-secret
      existingSecretPasswordKey: redis-password
  persistence:
    enabled: true
    storageClass: longhorn
    nextcloudData:
      enabled: true
      size: 256Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
