apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mail-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        mailPassword: {{` "{{ .mailPassword }}" `}}
  data:
    - secretKey: mailPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /overleaf
        property: mailPassword
