elementweb:
  ingress:
    enabled: true
    className: public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: relay.mbund.org
      mbund.org/dns-server: internal
      hajimari.io/appName: Element
      hajimari.io/icon: chat
      hajimari.io/group: External
    hosts:
      - host: &host chat.mbund.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *host
  config:
    default:
      base_url: https://mbund.org
      server_name: mbund.org
