searxng:
  searxng:
    config:
      general:
        instance_name: "Search"
      server:
        method: "GET"
      search:
        autocomplete: "google"
      ui:
        query_in_title: true
      outgoing:
        request_timeout: 3.0
        max_request_timeout: 30.0
        proxies:
          http: socks5://tor:9050
          https: socks5://tor:9050
        using_tor_proxy: true
        extra_proxy_timeout: 60.0
  ingress:
    main:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
        mbund.org/dns-server: internal
        hajimari.io/appName: Search
        hajimari.io/icon: search
        hajimari.io/group: External
      hosts:
        - host: &host searxng.mbund.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: searxng-tls-certificate
          hosts:
            - *host
