searxng:
  searxng:
    config:
      general:
        instance_name: "Search"
      server:
        method: "GET"
      search:
        autocomplete: "google"
        formats: [html, json]
      ui:
        query_in_title: true
      outgoing:
        request_timeout: 15.0
        max_request_timeout: 30.0
        proxies:
          all://: socks5h://tor:9050
        # using_tor_proxy: true
  ingress:
    main:
      enabled: true
      ingressClassName: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
      hosts:
        - host: &host search.mbund.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: searxng-tls-certificate
          hosts:
            - *host
