searxng:
  image:
    name: searxng/searxng:2023.5.13-1fc268a5
    pullPolicy: IfNotPresent
  searxng:
    config:
      general:
        instance_name: "Search"
      server:
        method: "GET"
      search:
        autocomplete: "google"
  ingress:
    main:
      enabled: true
      ingressClassName: relay-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
        hajimari.io/appName: Search
        hajimari.io/icon: mdi:search
      hosts:
        - host: &host searxng.mbund.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: searxng-tls-certificate
          hosts:
            - *host
