app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: searxng/searxng
            tag: latest
  service:
    main:
      ports:
        http:
          port: 8080
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
      hosts:
        - host: &host search.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: searxng-tls-certificate
  persistence:
    config-file:
      type: configMap
      name: searxng-configmap
      globalMounts:
        - path: /etc/searxng/settings.yaml
          subPath: settings.yaml
          readOnly: true
