apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor
  template:
    metadata:
      labels:
        app: tor
    spec:
      containers:
        - name: tor
          image: alpine:latest
          command: ['apk', 'add', 'tor', '&&', 'tor']
---
apiVersion: v1
kind: Service
metadata:
  name: tor
spec:
  selector:
    app: tor
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050
