apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor
  template:
    metadata:
      labels:
        app: tor
    spec:
      containers:
        - name: tor
          image: alpine:latest
          command: ['sh', '-c', 'apk add tor && tor -f /torrc']
          volumeMounts:
            - name: tor-config
              mountPath: /torrc
              subPath: torrc
      volumes:
        - name: tor-config
          configMap:
            name: tor-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tor-config
data:
  torrc: |
    SocksPort 0.0.0.0:9050 IPv6Traffic
    ExitNodes {US}
---
apiVersion: v1
kind: Service
metadata:
  name: tor
spec:
  selector:
    app: tor
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050
