apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        nextcloud-username: admin
        nextcloud-password: {{` "{{ .password }}" `}}
        nextcloud-token: {{` "{{ .token }}" `}}
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /nextcloud
        property: admin-password
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /nextcloud
        property: token
