apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        nextcloud-username: admin
        smtp-host: mbund.org
        nextcloud-password: {{` "{{ .password }}" `}}
        nextcloud-token: {{` "{{ .token }}" `}}
        smtp-username: {{` "{{ .smtpusername }}" `}}
        smtp-password: {{` "{{ .smtppassword }}" `}}
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /nextcloud
        property: admin-password
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /nextcloud
        property: token
    - secretKey: smtpusername
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /nextcloud
        property: smtp-username
    - secretKey: smtppassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /nextcloud
        property: smtp-password
