apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        db-password: {{` "{{ .password }}" `}}
        password: {{` "{{ .password }}" `}}
        postgres-password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: /nextcloud/postgres
        property: password
