apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: longhorn-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required "
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: homelab.tail22829.ts.net
    hajimari.io/icon: nas
spec:
  ingressClassName: private-nginx
  rules:
    - host: &host longhorn.mbund.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
  tls:
    - secretName: longhorn-tls-certificate
      hosts:
        - *host
