apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mail-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        mailPassword: >-
          {{ .mail-password }}
  data:
    - secretKey: mail-password
      remoteRef:
        key: /overleaf
        property: mail-password
