qbittorrent:
  env:
    TZ: America/New_York
    DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
  service:
    bittorrent:
      enabled: true
  ingress:
    main:
      enabled: true
      ingressClassName: private-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: 100.74.37.74
        hajimari.io/appName: QBittorrent
        hajimari.io/icon: filmstrip
      hosts:
        - host: &qbittorrent_host qbittorrent.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 8080
      tls:
        - secretName: qbittorrent-tls-certificate
          hosts:
            - *qbittorrent_host
  addons:
    vpn:
      enabled: true
      env:
        - name: TZ
          value: America/New_York
        - name: VPN_TYPE
          value: wireguard
        - name: VPN_SERVICE_PROVIDER
          value: mullvad
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: wg-private-key
              name: vpn-secret
        - name: WIREGUARD_ADDRESSES
          valueFrom:
            secretKeyRef:
              key: addresses
              name: vpn-secret
        - name: SERVER_CITIES
          valueFrom:
            secretKeyRef:
              key: city
              name: vpn-secret
