apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-mailserver-tls
  labels:
    app.kubernetes.io/name: docker-mailserver
spec:
  secretName: docker-mailserver-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mbund.org
  dnsNames:
    - "mbund.org"
    - "*.mbund.org"
