kind: ConfigMap
apiVersion: v1
metadata:
  name: docker-mailserver-config
  labels:
    app.kubernetes.io/name: docker-mailserver-config
data:
  postfix-main.cf: |
    postscreen_upstream_proxy_protocol = haproxy
  postfix-master.cf: |
    smtp/inet/postscreen_upstream_proxy_protocol=haproxy
    submission/inet/smtpd_upstream_proxy_protocol=haproxy
    smtps/inet/smtpd_upstream_proxy_protocol=haproxy
  dovecot.cf: |
    # All tailscale ips to send PROXY messages
    haproxy_trusted_networks = 100.64.0.0/10, 127.0.0.0/8
    service imap-login {
      inet_listener imap {
        haproxy = yes
      }
      inet_listener imaps {
        haproxy = yes
      }
    }
