apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-mailserver-configs
  labels:
    app.kubernetes.io/name: docker-mailserver
data:
  10-master.conf: |
    mail_max_userip_connections = 100

    #default_process_limit = 100
    #default_client_limit = 1000

    # Default VSZ (virtual memory size) limit for service processes. This is mainly
    # intended to catch and kill processes that leak memory before they eat up
    # everything.
    #default_vsz_limit = 256M

    # Login user is internally used by login processes. This is the most untrusted
    # user in Dovecot system. It shouldn't have access to anything at all.
    #default_login_user = dovenull

    # Internal user is used by unprivileged processes. It should be separate from
    # login user, so that login processes can't disturb other processes.
    #default_internal_user = dovecot

    service imap-login {
      inet_listener imap {
        #port = 143
      }
      inet_listener imaps {
        port = 993
        ssl = yes
      }

      # Number of connections to handle before starting a new process. Typically
      # the only useful values are 0 (unlimited) or 1. 1 is more secure, but 0
      # is faster. <doc/wiki/LoginProcess.txt>
      #service_count = 1

      # Number of processes to always keep waiting for more connections.
      #process_min_avail = 0

      # If you set service_count=0, you probably need to grow this.
      #vsz_limit = $default_vsz_limit
    }

    service pop3-login {
      inet_listener pop3 {
        #port = 110
      }
      inet_listener pop3s {
        port = 995
        ssl = yes
      }
    }

    service lmtp {
      unix_listener lmtp {
        mode = 0660
        group = postfix
      }

      # Create inet listener only if you can't use the above UNIX socket
      #inet_listener lmtp {
        # Avoid making LMTP visible for the entire internet
        #address =
        #port =
      #}
    }

    service imap {
      # Most of the memory goes to mmap()ing files. You may need to increase this
      # limit if you have huge mailboxes.
      #vsz_limit = $default_vsz_limit

      # Max. number of IMAP processes (connections)
      #process_limit = 1024
    }

    service pop3 {
      # Max. number of POP3 processes (connections)
      #process_limit = 1024
    }

    service auth {
      # auth_socket_path points to this userdb socket by default. It's typically
      # used by dovecot-lda, doveadm, possibly imap process, etc. Users that have
      # full permissions to this socket are able to get a list of all usernames and
      # get the results of everyone's userdb lookups.
      #
      # The default 0666 mode allows anyone to connect to the socket, but the
      # userdb lookups will succeed only if the userdb returns an "uid" field that
      # matches the caller process's UID. Also if caller's uid or gid matches the
      # socket's uid or gid the lookup succeeds. Anything else causes a failure.
      #
      # To give the caller full permissions to lookup all users, set the mode to
      # something else than 0666 and Dovecot lets the kernel enforce the
      # permissions (e.g. 0777 allows everyone full permissions).
      unix_listener auth-userdb {
        mode = 0666
        user = docker
        group = docker
      }

      unix_listener auth-master {
        mode = 0600
        user = docker
        group = docker
      }

      # Postfix smtp-auth
      unix_listener /var/spool/postfix/private/auth {
        mode = 0666
        user = docker
        group = docker
      }

      # Auth process is run as this user.
      #user = $default_internal_user
    }

    service auth-worker {
      # Auth worker process is run as root by default, so that it can access
      # /etc/shadow. If this isn't necessary, the user should be changed to
      # $default_internal_user.
      #user = root
    }

    service dict {
      # If dict proxy is used, mail processes should have access to its socket.
      # For example: mode=0660, group=vmail and global mail_access_groups=vmail
      unix_listener dict {
        #mode = 0600
        #user =
        #group =
      }
    }
  15-mailboxes.conf: |
    ##
    ## Mailbox definitions
    ##

    # NOTE: Assumes "namespace inbox" has been defined in 10-mail.conf.
    namespace inbox {

      #mailbox name {
        # auto=create will automatically create this mailbox.
        # auto=subscribe will both create and subscribe to the mailbox.
        #auto = no

        # Space separated list of IMAP SPECIAL-USE attributes as specified by
        # RFC 6154: \All \Archive \Drafts \Flagged \Junk \Sent \Trash
        #special_use =
      #}

      # These mailboxes are widely used and could perhaps be created automatically:
      mailbox Drafts {
        auto = subscribe
        special_use = \Drafts
      }
      mailbox Junk {
        auto = subscribe
        special_use = \Junk
      }
      mailbox Trash {
        auto = subscribe
        special_use = \Trash
      }
      mailbox Archive {
        auto = subscribe
        special_use = \Archive
      }

      # For \Sent mailboxes there are two widely used names. We'll mark both of
      # them as \Sent. User typically deletes one of them if duplicates are created.
      mailbox Sent {
        auto = subscribe
        special_use = \Sent
      }
    #  mailbox "Sent Messages" {
    #    special_use = \Sent
    #  }

      # If you have a virtual "All messages" mailbox:
      #mailbox virtual/All {
      #  special_use = \All
      #}

      # If you have a virtual "Flagged" mailbox:
      #mailbox virtual/Flagged {
      #  special_use = \Flagged
      #}
    }
  jail.local: |
    [DEFAULT]

    # "bantime" is the number of seconds that a host is banned.
    bantime = 3h

    # A host is banned if it has generated "maxretry" during the last "findtime"
    # seconds.
    findtime = 10m

    # "maxretry" is the number of failures before a host get banned.
    maxretry = 3

    # "ignoreip" can be a list of IP addresses, CIDR masks or DNS hosts. Fail2ban
    # will not ban a host which matches an address in this list. Several addresses
    # can be defined using space (and/or comma) separator.
    ignoreip = 127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16

    # default ban action
    # nftables-multiport: block IP only on affected port
    # nftables-allports:  block IP on all ports
    banaction = nftables-allports

    [dovecot]
    enabled = true

    [postfix]
    enabled = true

    [postfix-sasl]
    enabled = true

    # This jail is used for manual bans.
    # To ban an IP address use: setup.sh fail2ban ban <IP>
    [custom]
    enabled = true
    bantime = 180d
    port = smtp,pop3,pop3s,imap,imaps,submission,submissions,sieve
