apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mailserver
  labels:
    app.kubernetes.io/name: docker-mailserver
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: docker-mailserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docker-mailserver
    spec:
      serviceAccountName: tailscale
      containers:
        - name: mailserver
          image: mailserver/docker-mailserver:12.1.0
          envFrom:
            - configMapRef:
                name: docker-mailserver-env
          ports:
            - containerPort: 25
              protocol: TCP
              name: smtp
            - containerPort: 143
              protocol: TCP
              name: imap
            - containerPort: 587
              protocol: TCP
              name: submission
            - containerPort: 993
              protocol: TCP
              name: imaps
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - |
                  ! supervisorctl status | grep -E "mailserver" | grep -v RUNNING
            initialDelaySeconds: 15
            timeoutSeconds: 1
            failureThreshold: 3
          volumeMounts:
            - name: config
              subPath: postfix-main.cf
              mountPath: /tmp/docker-mailserver/postfix-main.cf
              readOnly: true
            - name: config
              subPath: postfix-master.cf
              mountPath: /tmp/docker-mailserver/postfix-master.cf
              readOnly: true
            - name: config
              subPath: dovecot.cf
              mountPath: /tmp/docker-mailserver/dovecot.cf
              readOnly: true

            - name: cert
              mountPath: /tmp/cert

            - name: data
              mountPath: /tmp/docker-mailserver
              subPath: config
            - name: data
              mountPath: /var/mail
              subPath: mail
            - name: data
              mountPath: /var/mail-state
              subPath: mail-state
            - name: data
              mountPath: /var/log/mail
              subPath: log

            - name: opendkim
              mountPath: /tmp/docker-mailserver/opendkim/KeyTable
              subPath: KeyTable
              readOnly: true
            - name: opendkim
              mountPath: /tmp/docker-mailserver/opendkim/SigningTable
              subPath: SigningTable
              readOnly: true
            - name: opendkim
              mountPath: /tmp/docker-mailserver/opendkim/TrustedHosts
              subPath: TrustedHosts
              readOnly: true
            - name: opendkim
              mountPath: /tmp/docker-mailserver/opendkim/keys/mbund.org/mail.private
              subPath: mail.private
              readOnly: true
          resources:
            requests:
              cpu: 40m
              memory: 1792Mi
            limits:
              cpu: 1050m
              memory: 3072Mi
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - "printf 'search svc.cluster.local cluster.local\nnameserver 10.43.0.10\nnameserver 1.1.1.1\n' > /etc/resolv.conf"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
        - name: tailscale
          imagePullPolicy: IfNotPresent
          image: ghcr.io/tailscale/tailscale:v1.44.0
          env:
            - name: TS_KUBE_SECRET
              value: tailscale-login-mailserver
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_AUTH_ONCE
              value: "true"
            - name: TS_ACCEPT_DNS
              value: "true"
            - name: TS_EXTRA_ARGS
              value: --hostname=homelab-mailserver # --exit-node=relay --exit-node-allow-lan-access
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 1024Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: docker-mailserver-data
        - name: config
          configMap:
            name: docker-mailserver-config
        - name: opendkim
          secret:
            secretName: docker-mailserver-opendkim
        - name: cert
          secret:
            secretName: docker-mailserver-tls
