apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-mailserver-opendkim
  labels:
    app.kubernetes.io/name: docker-mailserver
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      data:
        KeyTable: |
          mail._domainkey.mbund.org mbund.org:mail:/etc/opendkim/keys/mbund.org/mail.private
        SigningTable: |
          *@mbund.org mail._domainkey.mbund.org
        TrustedHosts: |
          127.0.0.1
          localhost
        mail.private: |
          {{ .opendkimKey }}
  data:
    - secretKey: opendkimKey
      remoteRef:
        key: secret/docker-mailserver
        property: opendkim-key
