apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-mailserver-data
  labels:
    app.kubernetes.io/name: docker-mailserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
