apiVersion: v1
kind: Service
metadata:
  name: docker-mailserver
  labels:
    app.kubernetes.io/name: docker-mailserver
spec:
  type: ClusterIP
  ports:
    - port: 25
      targetPort: smtp-transfer
      protocol: TCP
      name: smtp-transfer

    - port: 587
      targetPort: smpt-submission
      protocol: TCP
      name: smpt-submission
    - port: 465
      targetPort: smpt-submission-secure
      protocol: TCP
      name: smpt-submission-secure

    - port: 143
      targetPort: imap
      protocol: TCP
      name: imap
    - port: 993
      targetPort: imap-secure
      protocol: TCP
      name: imap-secure
  selector:
    app.kubernetes.io/name: docker-mailserver
