apiVersion: v1
kind: Service
metadata:
  name: docker-mailserver
  labels:
    app.kubernetes.io/name: docker-mailserver
spec:
  type: ClusterIP
  clusterIP: 10.43.2.60
  ports:
    - port: 25
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: 143
      targetPort: imap
      protocol: TCP
      name: imap
    - port: 587
      targetPort: submission
      protocol: TCP
      name: submission
    - port: 993
      targetPort: imaps
      protocol: TCP
      name: imaps
    - port: 8000
      targetPort: autodiscover
      protocol: TCP
      name: autodiscover
  selector:
    app.kubernetes.io/name: docker-mailserver
