external-dns:
  image:
    repository: registry.k8s.io/external-dns/external-dns
    tag: "v0.13.5"
    pullPolicy: IfNotPresent
  provider: pihole
  registry: noop
  extraArgs:
    - --pihole-server=http://pihole-web.pihole.svc.cluster.local
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
