external-dns:
  image:
    repository: registry.k8s.io/external-dns/external-dns
    tag: "v0.13.5"
    pullPolicy: IfNotPresent
  provider: pihole
  registry: noop
  env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: admin-secret
          key: password
  extraArgs:
    - --pihole-server=http://pihole-web.pihole.svc.cluster.local
    - --annotation-filter=mbund.org/dns-server in (internal)
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
