apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plausible-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        secret-key-base: {{` "{{ .secret-key-base }}" `}}
  data:
    - secretKey: secret-key-base
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /plausible
        property: secret-key-base
