apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plausible-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        SECRET_KEY_BASE: {{` "{{ .basekey }}" `}}
  data:
    - secretKey: basekey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /plausible
        property: basekey
