adguard-home:
  env:
    TZ: America/New_York
  ingress:
    main:
      enabled: true
      ingressClassName: private-nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: 100.74.37.74
        hajimari.io/appName: Adguard Home
        hajimari.io/icon: security-network
      hosts:
        - host: &host adguard.mbund.org
          paths:
            - path: /
      tls:
        - secretName: adguard-tls-certificate
          hosts:
            - *host
  service:
    dns-tcp:
      enabled: false
    dns-udp:
      enabled: false
  serviceAccount:
    name: tailscale
  sidecars:
    tailscale:
      name: tailscale
      imagePullPolicy: Always
      image: ghcr.io/tailscale/tailscale:v1.40.1
      env:
        - name: TS_KUBE_SECRET
          value: tailscale-login
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_AUTH_ONCE
          value: "true"
        - name: TS_EXTRA_ARGS
          value: --hostname=adguard
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  persistence:
    config:
      enabled: true
      retain: true
      mountPath: /opt/adguardhome/conf
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 4Gi
    data:
      enabled: true
      retain: true
      mountPath: /opt/adguardhome/work
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 4Gi
