minio:
  mode: standalone
  existingSecret: minio-user-secret
  persistence:
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 500Gi
  ingress:
    enabled: true
    ingressClassName: private-nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: 100.74.37.74
      hajimari.io/appName: MinIO
      hajimari.io/icon: mdi:nas
    hosts:
      - &host minio.mbund.org
    tls:
      - secretName: minio-tls-certificate
        hosts:
          - *host
