{
 "title": "Misc",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Server Time (America/New_York)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() * 1000.0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "Server Uptime Duration"
    }
   ]
  },
  {
   "title": "ArgoCD Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(argocd_app_info)", "legendFormat": "ArgoCD Application Count" }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(pihole_ads_percentage_today)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Internet Connectivity",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "min(monitor_status) OR vector(0)",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Total pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container_name!=\"POD\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}