{
 "title": "Speedtest",
 "description": "Dashboard for Speedtest Exporter https://github.com/MiguelNdeCarvalho/speedtest-exporter",
 "tags": [
  "Speedtest",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(speedtest_up, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(speedtest_up, job)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time((speedtest_download_bits_per_second > 0)[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time((speedtest_download_bits_per_second > 0)[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time((speedtest_download_bits_per_second > 0)[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time((speedtest_upload_bits_per_second > 0)[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time((speedtest_upload_bits_per_second > 0)[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time((speedtest_upload_bits_per_second > 0)[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time((speedtest_jitter_latency_milliseconds > 0)[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "max(max_over_time((speedtest_jitter_latency_milliseconds > 0)[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time((speedtest_jitter_latency_milliseconds > 0)[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Status of the Speedtest-Exporter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_up{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "ServerID (Last test done)",
   "type": "stat",
   "description": "ServerID of the last test done",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_server_id{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  { "title": "Graphics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Download Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6",
     "legendFormat": "Download Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Upload Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6",
     "legendFormat": "Upload Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Ping and Jitter (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Ping (ms)"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Jitter (ms)"
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second"
    },
    {
     "expr": "speedtest_upload_bits_per_second"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "Latency"
    },
    { "expr": "speedtest_server_id" }
   ]
  }
 ]
}