
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-signingkey-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        signing.key: {{` "{{ .signingkey }}" `}}
  data:
    - secretKey: signingkey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /synapse/signingkey
        property: signingkey
