app-template:
  image:
    repository: ghcr.io/blakeblackshear/frigate
    pullPolicy: IfNotPresent
    tag: 0.12.1
  strategy:
    type: Recreate
  env:
    TZ: America/New_York
  service:
    main:
      type: LoadBalancer
      ports:
        http:
          port: 5000
        rtsp:
          enabled: true
          port: 8554
          protocol: TCP
  ingress:
    main:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
      hosts:
        - host: &host nvr.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                name: frigate
      tls:
        - secretName: nvr-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: configMap
      name: frigate-config
    data:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 16Gi
      mountPath: /media
    shm:
      enabled: true
      type: hostPath
      hostPath: /dev/shm
