apiVersion: v1
kind: Pod
metadata:
  name: proxy
spec:
  serviceAccountName: "tailscale"
  initContainers:
    - name: configurer
      image: alpine
      securityContext:
        privileged: true
      command: ["/bin/sh"]
      args:
        - -c
        - apk add --no-cache iptables &&
          sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1 &&
          iptables -t nat -A POSTROUTING --source 100.64.0.0/10 --out-interface eth0 -j MASQUERADE
      resources:
        requests:
          cpu: 1m
          memory: 1Mi
  containers:
    - name: tailscale
      imagePullPolicy: Always
      image: "ghcr.io/tailscale/tailscale:latest"
      env:
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
              optional: true
        - name: TS_DEST_IP
          value: "10.43.219.6"
        - name: TS_AUTH_ONCE
          value: "true"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
