apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        wg-private-key: {{` "{{ .wgkey }}" `}}
        addresses: {{` "{{ .addresses }}" `}}
        city: {{` "{{ .city }}" `}}
  data:
    - secretKey: wgkey
      remoteRef:
        key: /vpn
        property: wgkey
    - secretKey: addresses
      remoteRef:
        key: /vpn
        property: addresses
    - secretKey: city
      remoteRef:
        key: /vpn
        property: city
