app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: plausible/analytics
            tag: v2.0.0
          command:
            - /bin/sh
            - -x
            - -c
            - /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run
          env:
            - name: TZ
              value: America/New_York
            - name: BASE_URL
              value: https://plausible.mbund.org
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@plausible-postgresql:5432/plausible_db"
            - name: CLICKHOUSE_DATABASE_URL
              value: "http://clickhouse:password@plausible-clickhouse:8123/plausible_events_db"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY_BASE
                  name: plausible-secret
            - name: MAXMIND_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: MAXMIND_LICENSE_KEY
                  name: plausible-secret
  service:
    main:
      ports:
        http:
          port: 8000
  ingress:
    main:
      enabled: true
      className: public
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: relay.mbund.org
      hosts:
        - host: &host plausible.mbund.org
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: plausible-tls-certificate
          hosts:
            - *host
postgresql:
  image:
    tag: 14
  auth:
    username: postgres
    password: postgres
    database: plausible_db
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi
clickhouse:
  shards: 1
  replicaCount: 1
  zookeeper:
    enabled: false
  auth:
    username: clickhouse
    password: password
    database: plausible_events_db
  initdbScripts:
    db-init.sql: |
      CREATE DATABASE IF NOT EXISTS plausible_events_db
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
