pihole:
  image:
    tag: "2023.05.2"
  extraEnvVars:
    TZ: America/New_York
    DNSMASQ_USER: root
  ingress:
    enabled: true
    ingressClassName: private
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
      mbund.org/dns-server: internal
      hajimari.io/appName: Pi-hole
      hajimari.io/icon: security-network
      hajimari.io/group: Internal
    path: /admin
    hosts:
      - &host pihole.mbund.org
    tls:
      - secretName: pihole-tls-certificate
        hosts:
          - *host
  persistentVolumeClaim:
    enabled: true
    storageClass: longhorn
  admin:
    existingSecret: admin-secret
