pihole:
  image:
    tag: "2023.05.2"
  extraEnvVars:
    TZ: America/New_York
    DNSMASQ_USER: root
    DNSMASQ_LISTENING: all
  ingress:
    enabled: true
    ingressClassName: private
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: private-relay.mbund.org
      hajimari.io/appName: Pi-hole
      hajimari.io/icon: security-network
      hajimari.io/group: Internal
    path: /admin
    hosts:
      - &host pihole.mbund.org
    tls:
      - secretName: pihole-tls-certificate
        hosts:
          - *host
  persistentVolumeClaim:
    enabled: true
    storageClass: longhorn
  admin:
    existingSecret: admin-secret
  extraContainers:
    - name: tailscale
      imagePullPolicy: IfNotPresent
      image: ghcr.io/tailscale/tailscale:v1.44.0
      command: ["/bin/sh"]
      args:
        - -c
        - printf 'search pihole.svc.cluster.local svc.cluster.local cluster.local\nnameserver 10.43.0.10\nnameserver 127.0.0.1\nnameserver 1.1.1.1\n' > /etc/resolv.conf &&
          /usr/local/bin/containerboot
      env:
        - name: TS_KUBE_SECRET
          value: tailscale-login
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_AUTH_ONCE
          value: "true"
        - name: TS_ACCEPT_DNS
          value: "true"
        - name: TS_EXTRA_ARGS
          value: --hostname=homelab-dns --accept-dns=false
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 500m
          memory: 1024Mi
  hostname: pihole-kubernetes
  podAnnotations:
    prometheus.io/port: "9617"
    prometheus.io/scrape: "true"
  monitoring:
    podMonitor:
      enabled: true
    sidecar:
      enabled: true
      image:
        tag: v0.4.0
  DNS1: &unbound-ip 10.43.1.60
  DNS2: ""
unbound:
  replicaCount: 1
  clusterIP: *unbound-ip
  containers:
    unbound:
      config:
        rootHints:
          enable: false
