pihole:
  pihole:
    virtualHost: pihole.mbund.org
    timezone: America/New_York
    image:
      tag: "2023.05.2"
    sidecars:
      - name: tailscale
        imagePullPolicy: IfNotPresent
        image: ghcr.io/tailscale/tailscale:v1.40.1
        env:
          - name: TS_KUBE_SECRET
            value: tailscale-login
          - name: TS_USERSPACE
            value: "false"
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                name: tailscale-auth
                key: TS_AUTHKEY
          - name: TS_AUTH_ONCE
            value: "true"
          - name: TS_EXTRA_ARGS
            value: --hostname=pihole
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
  serviceAccount:
    create: false
    name: tailscale
  persistence:
    enabled: true
    storageClass: longhorn
