# Gitea
- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true

# Longhorn
- path: longhorn/auth
  data:
    - key: password
      length: 32
      special: true

# Matrix Synapse
- path: synapse/postgresql
  data:
    - key: password
      length: 32
      special: true
