apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-postgresql-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        postgres-password: {{` "{{ .postgres_password }}" `}}
  data:
    - secretKey: postgres_password
      remoteRef:
        key: /synapse/postgresql
        property: postgres_password
