apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ ".Values.matrix-synapse.signingkey.existingSecret" }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        signing.key: {{` "{{ .signing.key }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: /synapse/signingkey
        property: signing.key
