apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-image-renderer
  name: grafana-image-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-image-renderer
  template:
    metadata:
      labels:
        app: grafana-image-renderer
    spec:
      containers:
        - name: grafana-image-renderer
          imagePullPolicy: Always
          image: grafana/grafana-image-renderer:3.7.2
          env:
            - name: RENDERING_MODE
              value: "default"
            - name: RENDERING_CLUSTERING_MODE
              value: "default"
            - name: RENDERING_CLUSTERING_MAX_CONCURRENCY
              value: "5"
            - name: RENDERING_DUMPIO
              value: "true"
            - name: RENDERING_ARGS
              value: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu,--window-size=1280x758"
            - name: TZ
              value: America/New_York
---
kind: Service
apiVersion: v1
metadata:
  name: grafana-image-renderer
spec:
  selector:
    app: grafana-image-renderer
  type: ClusterIP
  ports:
    - name: api
      port: 8081
      targetPort: 8081
      protocol: TCP
