matrix-synapse:
  serverName: mbund.org
  publicServerName: matrix.mbund.org
  ingress:
    className: public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: relay.mbund.org
    tls:
      - secretName: matrix-tls-certificate
        hosts:
          - matrix.mbund.org
  wellknown:
    enabled: true
  signingkey:
    job:
      enabled: false
    existingSecret: synapse-signingkey-secret
  postgresql:
    existingSecret: synapse-postgres-secret
    auth:
      existingSecret: synapse-postgres-secret
    primary:
      persistence:
        storageClass: longhorn
  persistence:
    storageClass: longhorn
