ingress-nginx:
  controller:
    config:
      custom-http-errors: >-
        401,403,404,500,501,502,503
    ingressClassResource:
      name: relay-nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/relay-ingress-nginx"
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      type: ClusterIP
      clusterIP: 10.43.0.62
  defaultBackend:
    enabled: true
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: latest
    extraEnvs:
      - name: TEMPLATE_NAME
        value: app-down
      - name: SHOW_DETAILS
        value: "true"
  tcp:
    25565: minecraft/minecraft-minecraft:25565
