penpot:
  global:
    postgresqlEnabled: true
    redisEnabled: true
  persistence:
    enabled: true
    storageClass: longhorn
  config:
    publicURI: https://penpot.mbund.org
    postgresql:
      username: example
      password: secretpassword
      database: penpot
