apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-user-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        rootUser: root
        rootPassword: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        key: /minio/user
        property: password
