argo-cd:
  global:
    domain: &host argocd2.testing.mbund.org
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
    cm:
      resource.ignoreResourceUpdatesEnabled: true
      resource.customizations.ignoreResourceUpdates.all: |
        jsonPointers:
          - /status
  server:
    ingress:
      enabled: true
      ingressClassName: private
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: private-relay.testing.mbund.org
      tls:
      - secretName: argocd2-tls-certificate
        hosts:
          - *host
    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: true
  dex:
    enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
argocd-apps:
  applicationsets:
    root:
      namespace: argocd
      generators:
        - git:
            repoURL: &repoURL https://github.com/mbund/homelab
            revision: &revision v2
            directories:
              - path: system/*
              - path: apps/*
      template:
        metadata:
          name: '{{path.basename}}'
        spec:
          destination:
            name: in-cluster
            namespace: '{{path.basename}}'
          project: default  # TODO
          source:
            repoURL: *repoURL
            path: '{{path}}'
            targetRevision: *revision
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            retry:
              limit: 10
              backoff:
                duration: 1m
                factor: 2
                maxDuration: 16m
            syncOptions:
              - CreateNamespace=true
              - ApplyOutOfSyncOnly=true
              - ServerSideApply=true
