apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - name: wireguard
      protocol: UDP
      port: 51820
      targetPort: 51820
      nodePort: 31820
